const types = {
  TODO_ITEM: 'TODO_ITEM',
  TODO_LIST: 'TODO_LIST',
  SEARCH_CRITERIA: 'SEARCH_CRITERIA',
  USER_INFO: 'USER_INFO',
  DELETE_USER_INFO: 'DELETE_USER_INFO',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  ROUTER_PATH: 'ROUTER_PATH',
  IS_HAS_APPROVAL: 'IS_HAS_APPROVAL',
  IS_HAS_INPROGRESS: 'IS_HAS_INPROGRESS',
  RESOURCE_DIALOG_VISIBLEADAT: 'RESOURCE_DIALOG_VISIBLEADAT',
  ACTUALTOTAL: 'ACTUALTOTAL',
}

export default types;
